### ISSUE TITLE
This is fantastic.

### ISSUE THREAD

**Issue by Econ808** [lucashusted/pystout#1]
Please make some noise about this package! It has saved me so much time and pain. 

There are other packages that attempt what you are doing, yet haven't managed to combine output from multiple statistical packages. It was only through a lucky Github follow that I actually stumbled upon this package, despite searching everywhere for a way to combining output from  multiple regressions carried out by `linearmodels.PanelOLS` and `statsmodels.OLS`.

Of course certain things are not plug-and-play (yet), such as `PanelOLS` not including R-squared values, however, these can be included manually in the `pystout` function 👍

**Comment by lucashusted** [comment]
Hi @Econ808 I would love to make some more noise. I have a few other packages that help with Econ too that you can check out. Any ideas where to publicize it? Not sure exactly how to do that exactly.

Also thanks for your kind words.

**Comment by Econ808** [comment]
Yeah, the best bet is probably to find issues that are unsolved, and mention that pystout might be the solution:

- A python implementation of stargazer (https://github.com/mwburke/stargazer) has an open issue where they seem to be stuck on developing the capability of combining Linearmodels and Statsmodels (https://github.com/mwburke/stargazer/issues/26). 

- Similarly, the first place I will look for answers is stackoverflow, and it happens that there is a unanswered question there aswell: (https://stackoverflow.com/questions/60620142/using-stargazer-to-output-latex-code-from-linearmodels-model-fit) 

Otherwise you might want to write a "Medium" article about the package - they somehow always show up at the top of my google searches.

**Comment by lucashusted** [comment]
Thanks Tobias! I made your changes and uploaded the new version to pypi. I am down to keep working on this and other projects with you too. I have a package to calculate propensity scores and another one to do regression discontinuity in python (I cheat and ship it over to R). I've been meaning to modify statsmodels to more intelligently drop variables that are collinear like in stata so that I never have the urge to use Stata again, for example. Hit me up.

**Comment by Econ808** [comment]
Yeah, I really hope that this slight push from R towards Python means that Python will be the preferred open-source statistical software. I am submitting my Master Thesis in two weeks, and I will not be working in a field where causality is a main focus (Data Science/ Business Intelligence), however, I might still find time to contribute.

In terms of enhancements to the python packages, you might want to open up issues to address these. In my pull request I changed the output such that a latex `table` instance was returned rather than the `tabular` instance. I am now doubting whether this unchangeable default is actually a good way to output the table, and that maybe a `table` instance should only be returned if a label or title is provided. Below a difference in how to create the same table (assuming label and title is provided in `result_table` and not `result_tabular)` using `tabular` and `table`, respectively:


![image](https://user-images.githubusercontent.com/36441764/99232694-890f9200-27f2-11eb-9d53-12c406ac21c5.png)


![image](https://user-images.githubusercontent.com/36441764/99232708-90cf3680-27f2-11eb-8842-1ada7e40eb26.png)

**Comment by lucashusted** [comment]
I have made the changes for the newest version. The default is a tabular though a table is written if title or label are explicitly specified. You can update to version 0.0.5.
