### ISSUE TITLE
Adding modstat variables?

### ISSUE THREAD

**Issue by mwood7** [lucashusted/pystout#3]
First, thanks for this!  Very nice.  

For a project I'm doing it would be useful to be able to report 'aic' and 'bic' in the modstat line.  I'm extremely new to GitHub so have never done pull requests etc.  Not wanting to mess things up, I'm just attaching your pystout.py file with the changes that allow AIC and BIC to be output (it was a very easy change, of course).  If it OK, please merge it with what you have after testing? (I had to rename it pystout.txt to attach).

One other thing you might want to include in your documentation for those who aren't LaTeX savvy is a link to quicklatex.com.  I found I can copy your output table and it renders nicely to something the user could drag into a Word document.  Me I've been using LaTeX since mid 1980's, but my collaborators not so much.  

[pystout.txt](https://github.com/lucashusted/pystout/files/5851761/pystout.txt)
![pystout_sample_output](https://user-images.githubusercontent.com/10778534/105404637-d132a280-5bef-11eb-9320-98a611a15210.png)

**Comment by lucashusted** [comment]
@mattwoodtx great suggestion. Added the feature and updated it here and on PyPI. Feel free to pull the new version.
